baseURL = 'https://rupakbiswas-2304.github.io/'
languageCode = 'en-us'
title = '@metaphor'
theme = 'hugo-theme-shell'
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = true
  
  [Params.Extensions]
  use = true
  ext = ".md" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Rupak's Portfolio!"
  [Params.Terminal]
  scheme = "Molokai"

  userName = "rupak"
  pcName = "lappychan"
  workDir = "myprojects"
  profile = "profile.md"

  ps1Delay = 20 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 10 # stdout speed : [description] , files in Params.Tree
  commandDelay = 10 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = "/description.md" 


  [Params.Tree]
  use = true
  folderName = "topics"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["PROJECTS", "/project.md"],
    ["BLOG", "/blog.md"],
    ["WRITEUPS", "/writeups.md"],
    ["NOTES","/notes.md"],
    ["ABOUT", "/about.md"],
    ["CONTACT ME", "/contact.md"]
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"